// Generated by Bisonc++ V2.4.0 on Mon Oct  4 15:55:37 2010 -0500

#ifndef ParserBase_h_included
#define ParserBase_h_included



class ParserBase
{
    public:
// $insert tokens

    // Symbolic tokens:
    enum Tokens__
    {
        TKN_VAR = 257,
        TKN_SEMICOLON,
        TKN_OP_EQUAL,
        TKN_OP_PLUS,
        TKN_INT,
        TKN_TYPE_INT,
        TKN_LPAREN,
        TKN_RPAREN,
        TKN_PRINT,
        TKN_TERMINATION,
        TKN_UNINITIALIZED,
    };
};

#endif

