#ifndef __INCLUDE_GUARD__GRAMMA_H__
#define __INCLUDE_GUARD__GRAMMA_H__

typedef enum {
     BR_TKN_DOT,
     BR_TKN_TERMINATION,
     BR_TKN_UNINITIALIZED,
     BR_TKN_SEMI,
     BR_TKN_FROM,
     BR_TKN_LETTER,
     BR_TKN_PARSE_ERROR,
     BR_TKN_SCHEMA,
     BR_TKN_NUMBER,
     BR_TKN_LITERAL,
     BR_TKN_WHERE,
     BR_TKN_SELECT,
     BR_TKN_IDENTIFIER,
     BR_TKN_SHOW,
     BR_TKN_SCHEMAS,
} T_GrammaTokenID;

#endif /* __INCLUDE_GUARD__GRAMMA_H__ */
