/* PURPOSE: Test Buffer_move_away_upfront_content()
 *
 * The tested function shall free some space in the rear buffer,
 * so that old content can be reloaded. Detailed comment, see function
 * definition.
 *
 * Moving depends on:   * _read_p, 
 *                      * _lexeme_start_p
 *                      * whether the buffer contains the end of file or not.
 *                      * begin_character_index
 *                      * QUEX_TYPE_CHARACTER
 *
 * The last one is controlled by a compile-time parameter. The others are
 * varried dynamically. The begin_character_index is dealt with by setting
 * the end character index to 'content size + 3'. So there will be cases
 * where the begin character index == 0 and therefore prohibits moving.
 *
 * EXPERIMENT: Setup buffer of 5 elements.
 *
 * Multiple versions of compiled objects exist:
 *
 *        QUEX_TYPE_CHARACTER:  uint8_t, uint16_t, uint32_t           
 *
 * The parameters '_read_p' and '_lexeme_start_p' are varried the following
 * way:
 *    _lexeme_start_p -> begin ... end of buffer
 *    _read_p         -> begin, 
 *                       _lexeme_start_p-1, _lexeme_start_p, _lexeme_start_p+1, 
 *                       end of buffer
 *    end of file     = true, false
 *
 * Before each copying process the buffer is reset into its initial state. Test
 * cases are generated by hwuts generator, i.e. 'hwut gen this-file.c'.      
 *
 * CHOICES: Character index at begin of buffer: "cib=0", "cib=1", "cib=2".
 *                                                                           */

/* 
<<hwut-iterator: G>> 
------------------------------------------------------------------------
#include <stdint.h>
------------------------------------------------------------------------
    int lexeme_start_i;    int read_i;                                   int eof_f; 
    |0:5|;                 |lexeme_start_i-1:lexeme_start_i+1| in |0:5|; [0, 1];

------------------------------------------------------------------------
*/

#include <move_away_upfront_content-gen.h>
#include "commonly-pasted.cpp" /* requires 'G_t' from above header. */

static QUEX_TYPE_CHARACTER  content[] = { '6', '5', '4', '3', '2', '1' }; 
ptrdiff_t                   ContentSize = sizeof(content)/sizeof(content[0]);
static QUEX_TYPE_CHARACTER  memory[11];
const  ptrdiff_t            MemorySize = sizeof(memory)/sizeof(memory[0]);


int
main(int argc, char** argv)
{
    QUEX_NAME(Buffer)         buffer;
    G_t                       it;
    QUEX_TYPE_CHARACTER       lsp_char, rp_char;
    QUEX_TYPE_STREAM_POSITION character_index_at_begin;

    if( cl_has(argc, argv, "--hwut-info") ) {
        printf("move_away_upfront_content: (BPC=%i);\n", 
               sizeof(QUEX_TYPE_CHARACTER));
        printf("CHOICES: cib=0, cib=1, cib=2;\n");
        return 0;
    }
    stderr = stdout;
    hwut_if_choice("cib=0") character_index_at_begin = 0;
    hwut_if_choice("cib=1") character_index_at_begin = 1;
    hwut_if_choice("cib=2") character_index_at_begin = 2;

    G_init(&it);
    
    printf("        lexeme_start_p: read_p: end_p: begin_ci: end_ci: buffer:\n");
    while( G_next(&it) ) {
        instantiate_iterator(&buffer, &it, 
                             &memory[0], MemorySize, 
                             &content[0], ContentSize);
        buffer.input.character_index_begin = character_index_at_begin;

        printf("\n-( %2i )---------------------------------------------\n", (int)G_key_get(&it));
        self_print(&buffer);

        lsp_char = *buffer._lexeme_start_p;
        rp_char  = *buffer._read_p;

        QUEX_NAME(Buffer_move_away_upfront_content)(&buffer);

        self_print(&buffer);

        /* Asserts after print, so that errors appear clearly. */
        hwut_verify(lsp_char == *buffer._lexeme_start_p);
        hwut_verify(rp_char  == *buffer._read_p);

        QUEX_NAME(Buffer_destruct)(&buffer);
    }
}

